---
- name: Install Java (for SonarQube)
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes
  become: yes

- name: Download SonarQube
  get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip
    dest: /tmp/sonarqube.zip
  become: yes

- name: Install unzip
  apt:
    name: unzip
    state: present
  become: yes

- name: Extract SonarQube
  unarchive:
    src: /tmp/sonarqube.zip
    dest: /opt/
    remote_src: yes
  become: yes

- name: Create sonar user
  user:
    name: sonar
    system: yes
    shell: /bin/false
  become: yes

- name: Change ownership
  file:
    path: /opt/sonarqube-9.9.0.65466
    owner: sonar
    group: sonar
    recurse: yes
  become: yes

- name: Start SonarQube
  shell: "sudo -u sonar /opt/sonarqube-9.9.0.65466/bin/linux-x86-64/sonar.sh start"
  become: yes
